# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66b60529fefb65a7e83a6b5d45fbf5daa4cfc1b6f7f10ff4bcf3f4c05561f9858fbe2088f70713a37c7381759e87917385cf82fd16f4817013d75410bc005635

test:
  secret_key_base: 61038c9b7cf34f285c63fd739e30d3a12e0b1c90aa4a4dd7645a682c05f69534cea8a26a4bdc73048f4f6c4d233674290ef196a33a5fe3a9ed73066506ea5061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
